from simplevirtualmachine.bytecodes.instruction import Instruction

INVALID = Instruction(0)
IADD = Instruction(1)
ISUB = Instruction(2)
IMUL = Instruction(3)
IEQ = Instruction(5)
ILT = Instruction(4)
BR = Instruction(6, 1)
BRT = Instruction(7, 1)
BRF = Instruction(8, 1)
ICONST = Instruction(9,1)
LOAD = Instruction(10, 1)
GLOAD = Instruction(11,1)
STORE = Instruction(12, 1)
GSTORE = Instruction(13,1)
PUTS = Instruction(14)
POP = Instruction(15, 1)
CALL = Instruction(16, 1)
RET = Instruction(17, 1)
HALT = Instruction(18)
