from simplevirtualmachine.bytecodes.brf import BRF
from simplevirtualmachine.bytecodes.br import BR
from simplevirtualmachine.bytecodes.brt import BRT
from simplevirtualmachine.bytecodes.call import CALL
from simplevirtualmachine.bytecodes.gload import GLOAD
from simplevirtualmachine.bytecodes.gstore import GSTORE
from simplevirtualmachine.bytecodes.halt import HALT
from simplevirtualmachine.bytecodes.iadd import IADD
from simplevirtualmachine.bytecodes.iconst import ICONST
from simplevirtualmachine.bytecodes.ieq import IEQ
from simplevirtualmachine.bytecodes.iil import IIL
from simplevirtualmachine.bytecodes.imul import IMUL
from simplevirtualmachine.bytecodes.invalid import INVALID
from simplevirtualmachine.bytecodes.isub import ISUB
from simplevirtualmachine.bytecodes.load import LOAD
from simplevirtualmachine.bytecodes.pop import POP
from simplevirtualmachine.bytecodes.puts import PUTS 
from simplevirtualmachine.bytecodes.ret import RET
from simplevirtualmachine.bytecodes.store import STORE

